name: workflow for other branches
on:
  push:
    branches:
      - feature
      - fix
      - chore
      - hotfix

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build